"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const express_1 = __importDefault(require("express"));
const errors_1 = require("../middlewares/errors");
const middlewares_1 = __importDefault(require("../middlewares/middlewares"));
const internal_routes_1 = __importDefault(require("./internal.routes"));
const external_routes_1 = __importDefault(require("./external.routes"));
const app = (0, express_1.default)();
app.use(middlewares_1.default);
app.set("view engine", "ejs");
app.use(internal_routes_1.default);
app.use("/api", external_routes_1.default);
app.use(errors_1.not_found);
app.use(errors_1.error_response);
exports.default = app;
