"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("../routes/auth.routes"));
const product_routes_1 = __importDefault(require("../routes/product.routes"));
const upload_routes_1 = __importDefault(require("../routes/upload.routes"));
const setting_routes_1 = __importDefault(require("../routes/setting.routes"));
const supplier_routes_1 = __importDefault(require("../routes/supplier.routes"));
const admin_panel_routes_1 = __importDefault(require("../routes/admin.panel.routes"));
const supplier_history_routes_1 = __importDefault(require("../routes/supplier.history.routes"));
const customer_routes_1 = __importDefault(require("../routes/customer.routes"));
const barcode_routes_1 = __importDefault(require("../routes/barcode.routes"));
const vat_routes_1 = __importDefault(require("../routes/vat.routes"));
const discount_routes_1 = __importDefault(require("../routes/discount.routes"));
const payment_method_routes_1 = __importDefault(require("../routes/payment.method.routes"));
const sale_routes_1 = __importDefault(require("../routes/sale.routes"));
const brand_routes_1 = __importDefault(require("../routes/brand.routes"));
const warranty_routes_1 = __importDefault(require("../routes/warranty.routes"));
const expense_routes_1 = __importDefault(require("../routes/expense.routes"));
const expense_category_routes_1 = __importDefault(require("../routes/expense.category.routes"));
const page_routes_1 = __importDefault(require("../routes/page.routes"));
const tax_routes_1 = __importDefault(require("../routes/tax.routes"));
const router = (0, express_1.Router)();
// external route start with "/api/__route_name"
router.get(`/health`, (_, res) => res.status(200).json({ message: "ok" }));
router.use("/auth", auth_routes_1.default);
router.use("/setting", setting_routes_1.default);
router.use("/upload", upload_routes_1.default);
router.use("/product", product_routes_1.default);
router.use("/admin", admin_panel_routes_1.default);
router.use("/supplier", supplier_routes_1.default);
router.use("/supplier-history", supplier_history_routes_1.default);
router.use("/customer", customer_routes_1.default);
router.use("/barcode", barcode_routes_1.default);
router.use("/vat", vat_routes_1.default);
router.use("/payment-method", payment_method_routes_1.default);
router.use("/discount", discount_routes_1.default);
router.use("/sale", sale_routes_1.default);
router.use("/brand", brand_routes_1.default);
router.use("/expense", expense_routes_1.default);
router.use("/expense-category", expense_category_routes_1.default);
router.use("/warranty", warranty_routes_1.default);
router.use("/page", page_routes_1.default);
router.use("/tax", tax_routes_1.default);
const externalRoutes = router;
exports.default = externalRoutes;
